//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pfeCLS_website.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Branche
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Branche()
        {
            this.Inscriptions = new HashSet<Inscription>();
        }
    
        public int ID_branche { get; set; }

        [Required(ErrorMessage = "Veuillez entrez le nom du branche.")]

        public string Nom_branche { get; set; }
        [Required(ErrorMessage = "Veuillez entrez le prix du branche.")]
        [RegularExpression("([1-9][0-9]*)")]
        public Nullable<decimal> prix_branche { get; set; }

        [Required(ErrorMessage = "Veuillez entrez les frais d'inscription pour cette branche.")]
        [RegularExpression("([1-9][0-9]*)")]
        public Nullable<decimal> frais_inscri { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Inscription> Inscriptions { get; set; }
    }
}
