//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pfeCLS_website.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Contact
    {
        public int id_msg { get; set; }

        [Required(ErrorMessage = "Veuillez saisir votre nom.")]
        public string Nom_msg { get; set; }

        [Display(Name = "Email Address")]
        [EmailAddress]
        [RegularExpression("^[_A-Za-z'`+-.]+([_A-Za-z0-9'+-.]+)*@([A-Za-z0-9-])+(\\.[A-Za-z0-9]+)*(\\.([A-Za-z]*){3,})$", ErrorMessage = "Saisissez l'adresse e-mail appropriée")]
        [Required(ErrorMessage = "non approprié de l'adresse e-mail.")]
        //[DataType(DataType.EmailAddress, ErrorMessage = "non approprié de l'adresse e-mail")]

        public string Email_msg { get; set; }

       
        public string Objet_msg { get; set; }

        [Required(ErrorMessage = "Veuillez saisir un message.")]
        public string Message_msg { get; set; }
    }
}
