//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pfeCLS_website.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Contact
    {
        public int id_msg { get; set; }
        [Required(ErrorMessage = "Veuillez saisir votre nom.")]
        public string Nom_msg { get; set; }
        public string Email_msg { get; set; }
        [Required(ErrorMessage = "Veuillez saisir un objet.")]
        public string Objet_msg { get; set; }
        [Required(ErrorMessage = "Veuillez saisir votre message.")]
        public string Message_msg { get; set; }
    }
}
