//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pfeCLS_website.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Inscription
    {
        public int id_part { get; set; }

        [Required(ErrorMessage = "Veuillez saisir votre nom.")]
        public string Nom_part { get; set; }

        [Required(ErrorMessage = "Veuillez saisir votre prenom.")]
        public string Prenom_part { get; set; }
        public Nullable<int> Age_part { get; set; }

        [Display(Name = "Email Address")]
        [EmailAddress]
        [RegularExpression("^[_A-Za-z'`+-.]+([_A-Za-z0-9'+-.]+)*@([A-Za-z0-9-])+(\\.[A-Za-z0-9]+)*(\\.([A-Za-z]*){3,})$", ErrorMessage = "Saisissez l'adresse e-mail appropriée")]
        [Required(ErrorMessage = "non approprié de l'adresse e-mail.")]
        //[DataType(DataType.EmailAddress, ErrorMessage = "non approprié de l'adresse e-mail")]

        public string Email_part { get; set; }

        [Required(ErrorMessage = "Veuillez saisir votre profil.")]
        public string Profil_part { get; set; }

        [Required(ErrorMessage = "Veuillez saisir votre adresse.")]
        public string Adresse_part { get; set; }

        [Required(ErrorMessage = "Veuillez saisir votre telephone.")]
        public string Tele_part { get; set; }

        public Nullable<System.DateTime> Date_Inscr { get; set; }

     
        public Nullable<int> ID_branche { get; set; }
    
        public virtual Branche Branche { get; set; }
    }
}
