//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pfeCLS_website.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Inscription
    {
        public int id_part { get; set; }
        [Required(ErrorMessage = "Saisir votre Nom.")]

        public string Nom_part { get; set; }
        [Required(ErrorMessage = "Saisir votre prenom.")]

        public string Prenom_part { get; set; }
        [Required(ErrorMessage = "Saisir votre age.")]

        public Nullable<int> Age_part { get; set; }
        [Required(ErrorMessage = "Saisir votre email.")]
        [DataType(DataType.EmailAddress, ErrorMessage = "E-mail non valide")]
        public string Email_part { get; set; }
        [Required(ErrorMessage = "Saisir votre profil.")]

        public string Profil_part { get; set; }
        [Required(ErrorMessage = "Saisir votre adresse.")]

        public string Adresse_part { get; set; }
        [Required(ErrorMessage = "Saisir votre numero.")]

        public string Tele_part { get; set; }
        public Nullable<System.DateTime> Date_Inscr { get; set; }

       
        public Nullable<int> ID_branche { get; set; }
    
        public virtual Branche Branche { get; set; }
    }
}
