//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pfeCLS_website.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web;

    public partial class Offre
    {
        public int Id_Off { get; set; }
        public string Tittre_Off { get; set; }
        public string Descr_Off { get; set; }
        public string Imag_Off { get; set; }
        public Nullable<int> Id_Cat { get; set; }
    
        public virtual Categorie Categorie { get; set; }

   

    }
}
